# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [3]:
import numpy as np 

arr1 = np.random.randint(1,21,size=(5,5))
print(arr1)  # Output: [[ 1  2  3  4

arr1[:,2] = 1

print(arr1)

[[ 3 14  2 16  9]
 [ 9 18 19 18 17]
 [ 6 15 14 20 12]
 [ 8 10  2  9  3]
 [15  3  1  2 15]]
[[ 3 14  1 16  9]
 [ 9 18  1 18 17]
 [ 6 15  1 20 12]
 [ 8 10  1  9  3]
 [15  3  1  2 15]]


In [6]:
arr1 = np.random.randint(1,17,size=(4,4))
print(arr1)

np.fill_diagonal(arr1,0)
print(arr1)

[[ 6  4 11 10]
 [15  6 13 11]
 [13 16  5 10]
 [ 8 16  7 10]]
[[ 0  4 11 10]
 [15  0 13 11]
 [13 16  0 10]
 [ 8 16  7  0]]


In [10]:
arr1 = np.random.randint(1,37,size=(6,6))
print(arr1)

print(arr1[2:5, 1:4])



[[13 33  1  8 15  5]
 [ 8 34 23 22 31  8]
 [ 2 27 14 24 29  8]
 [ 6 19  4 31 24 17]
 [ 1  8 14 23 13 27]
 [ 5 21 20 13 12 23]]
[[27 14 24]
 [19  4 31]
 [ 8 14 23]]


In [27]:
arr1 = np.random.randint(1,21,size=(5,5))
print(arr1)

border_elements = np.concatenate((arr1[0, :], arr1[-1, :], arr1[1:-1, 0], arr1[1:-1, -1]))
print(border_elements)



[[ 9 10 14 17  2]
 [19  2 14  3  1]
 [ 3 16 17 16 14]
 [ 2  3 15 18 14]
 [20  2  7 11 13]]
[ 9 10 14 17  2 20  2  7 11 13 19  3  2  1 14 14]


In [32]:
arr1 = np.random.randint(1,21,size=(3,4))
arr2 = np.random.randint(1,21,size=(3,4))
print(arr1)
print(arr2)
addition = (arr1+arr2)
print(addition)
subtraction=arr1-arr2
print(subtraction)
multiply = arr1*arr2
print(multiply)
division= arr1/arr2 
print(division)

[[13 18 15 17]
 [16 17  9  3]
 [13 10 17  9]]
[[ 8 20 13 14]
 [12  4 14 17]
 [14 14 18  4]]
[[21 38 28 31]
 [28 21 23 20]
 [27 24 35 13]]
[[  5  -2   2   3]
 [  4  13  -5 -14]
 [ -1  -4  -1   5]]
[[104 360 195 238]
 [192  68 126  51]
 [182 140 306  36]]
[[1.625      0.9        1.15384615 1.21428571]
 [1.33333333 4.25       0.64285714 0.17647059]
 [0.92857143 0.71428571 0.94444444 2.25      ]]


In [35]:
arr1 = np.random.randint(1,16,size=(4,4))
print(arr1)

row_sum = np.sum(arr1, axis=1)
column_sum = np.sum(arr1, axis=0)
print(row_sum)
print(column_sum)

[[ 6 11  6  8]
 [ 3 12 11  4]
 [ 5 11 12 11]
 [ 8  5  2  3]]
[31 30 39 18]
[22 39 31 26]


In [37]:
arr1 = np.random.randint(1,21,size=(5,5))
print(arr1)
print(np.mean(arr1))
print(np.median(arr1))
print(np.std(arr1))

[[ 5 10 13 17  7]
 [17 14 12  5 19]
 [ 5 20 11  4  2]
 [19  2  4 18  1]
 [11  7 12 15  8]]
10.32
11.0
5.8632414243317665


In [38]:
array = np.arange(1, 10).reshape((3, 3))
print("Original array:")
print(array)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalized_array = (array - mean) / std_dev

print("Normalized array:")
print(normalized_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
