In [3]:
###Numpy is a library for scientific computing in Python for arrays and matrices 

import numpy as np

## create array 

##1-D array 

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)   #1 row and 5 elements

array([[1, 2, 3, 4, 5]])

In [ ]:

#2-D array
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2)
arr2.shape #2 rows and 5 columns

[[1 2 3 4 5]
 [1 2 3 4 5]]


(2, 5)

In [12]:
arr=np.arange(0,10,2)
print(arr)
arr3=np.arange(0,10,2).reshape(5,1)
print(arr3)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
### Identity matrix 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape",arr.shape)
print("Number of Dimensions: ", arr.ndim)
print("Array size: ",arr.size)
print("Data type: ", arr.dtype)
print("In bytes", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape (2, 3)
Number of Dimensions:  2
Array size:  6
Data type:  int32
In bytes 4


In [21]:
### Numpy vectorised operations 

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

## Element wise addition
print(arr1+arr2)

print(arr1-arr2)

print(arr1*arr2)

print(arr1/arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [22]:
### Universal functions 

arr = np.array([1,2,3,4,5])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))


[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [27]:
## Universal functions(ufuncs)

## array slicing and indexing 

arr = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr[0,1])
print(arr[0][2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
3


In [29]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [30]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [33]:
arr[1:2,1:]

array([[6, 7, 8]])

In [34]:
## Modify array elements 

arr[0,0] = 100

In [35]:
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [37]:
arr[1:]=100

print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [38]:
### statistical concept ----Normalisation
## to have a mean of zero and standard deviation is 1

data = np.array([1,2,3,4,5])
mean = np.mean(data)
std = np.std(data)

#normalize the data 

norm_data = (data - mean) / std 
print(norm_data)


[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [40]:
data = np.array([1,2,3,4,5])
mean = np.mean(data)
print(mean)  # Output: 3.0
std = np.std(data)
print(std)  # Output: 1.4142135623730951
median = np.median(data)
print(median)  # Output: 3.0
var = np.var(data)
print(var)


3.0
1.4142135623730951
3.0
2.0


In [48]:
## Logical operation 

data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5
data[(data>5 )& (data<8)]

array([6, 7])